### PR TITLE
When calling simulate with a tx specified, wait for it to be included, then run the simulation

### PR DESCRIPTION
**Pull request by epheph**

### CODE REVIEW

**Comment by epheph** [comment]
@zeroXbrock

**Comment by zeroXbrock** [comment]
@epheph awesome -- exactly what we needed for this method. Code looks perfect, just need to test locally, and I also need to resolve that build warning, but I'll merge once that's done.

**Review by zeroXbrock — APPROVED** [review]

**Comment by zeroXbrock** [comment]
@epheph oh, I didn't realize that was missing. Did you try setting the block in the `inclusion` param?

this is what I was doing, but using the method directly w/ a standalone block monitor:
```ts
// assume `blockNumber` is in scope
matchmaker.simulateBundle({
    ...bundleParams,
    inclusion: {
        block: (tx?.blockNumber || blockNumber) - 1,
    },
    body: simBundle,
})
```

**Comment by epheph** [comment]
Oh, i expected it to be the last argument, it interprets that as the block-heigh to simulate? awesome and makes sense.

**Comment by zeroXbrock** [comment]
For now let's leave the block number to the user. Regardless of how we resolve the nonce issue, having this code in place still makes the method waaaay more useful.
We can make sims better (simulate in `targetBlock` instead of `targetBlock - 1`) on the backend without any changes here.
Merging.

**Pull request merged**
